name: doer
description: kumar properties doer application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0" #sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.1+1
  provider: ^6.0.0
  rxdart: ^0.27.1
  intl: ^0.17.0
  kf_drawer: ^1.2.1
  shared_preferences: ^2.0.6
  #device_info_plus: ^8.0.0
  package_info_plus: ^4.0.2
  font_awesome_flutter: ^9.0.0
  flutter_rounded_date_picker: ^3.0.4
  #http: ^0.13.2
  http:
  image_picker: ^0.8.3+3
 # image_picker: ^0.8.0
  #camera: ^0.5.7+2
  image_cropper: ^9.1.0
  dio: ^4.0.0
  photo_view: ^0.15.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20

 # new_version: any
  # upgrader:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true

  image_path: "assets/icons/app_icon.png" # flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  android: true
  ios: true

  #color: '#FFCC00'
  background_image: "assets/icons/image.png" # flutter pub run flutter_native_splash:create


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/connection_off.png
    - assets/icons/no_data_found.png
    - assets/icons/no_notifications.png
    - assets/icons/no-image.png
    - assets/icons/img.jpg
    - assets/icons/kp_logo.png
    - assets/icons/home.png
    - assets/icons/dpr.png
    - assets/icons/Handing.png
    - assets/icons/logout.png
    - assets/icons/mom.png
    - assets/icons/notifications.png
    - assets/icons/Quality_C.png
    - assets/icons/RERA.png
    - assets/icons/user.png
    - assets/icons/image.png
    - assets/icons/app_icon.png
    - assets/icons/no_image.png

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
